name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - name: Build Release
              run: dotnet publish -c Release -o ./publish

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./publish/**
                  generate_release_notes: true
